name: build

on:
  push:
    paths-ignore:
    - '**.md'
    - '**/[rR][eE][aA][dD][mM][eE]'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js 16.x
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.x

    - run: npm install
    - run: npm run all

    - name: Run action
      id: program
      uses: ./
      with:
        milliseconds: 3000
    - name: Check output
      run: echo "${{ steps.program.outputs.time }}"

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
