name: build

on:
  push:
    paths-ignore:
    - '**.md'
    - '**/[rR][eE][aA][dD][mM][eE]'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js 16.x
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.x

    - run: npm install
    - run: npm run all

    - name: Run action
      id: program
      uses: ./
      with:
        milliseconds: 3000
    - name: Check output
      run: echo "${{ steps.program.outputs.time }}"
